import { Injectable } from '@nestjs/common';
import PDFDocument from 'pdfkit';
import type { ProfessionalEstimateResult } from '@/modules/ai/services/ai.service';

type PdfMeta = {
  version: number;
  currency: string;
  createdAt: Date;
};

const COLORS = {
  primary: '#1a56db',
  primaryLight: '#e1effe',
  dark: '#111827',
  gray: '#4b5563',
  lightGray: '#9ca3af',
  border: '#d1d5db',
  white: '#ffffff',
  success: '#059669',
  warning: '#d97706',
  danger: '#dc2626',
  bgLight: '#f9fafb',
};

const FONT_SIZES = {
  title: 28,
  sectionTitle: 18,
  subTitle: 14,
  body: 10,
  small: 9,
  caption: 8,
};

@Injectable()
export class EstimatePdfService {
  async generate(
    estimate: ProfessionalEstimateResult,
    meta: PdfMeta,
  ): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({
        size: 'A4',
        margins: { top: 60, bottom: 60, left: 50, right: 50 },
        info: {
          Title: `Project Estimate - ${estimate.projectOverview.projectName}`,
          Author: 'Bolder Scope',
          Subject: 'Professional Project Estimate',
        },
        bufferPages: true,
      });

      const chunks: Buffer[] = [];
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      this.renderCoverPage(doc, estimate, meta);
      this.renderTableOfContents(doc);
      this.renderSection1(doc, estimate.projectOverview);
      this.renderSection2(doc, estimate.scope);
      this.renderSection3(doc, estimate.technicalArchitecture);
      this.renderSection4(doc, estimate.wbs, meta.currency);
      this.renderSection5(doc, estimate.timeline);
      this.renderSection6(doc, estimate.costCalculation);
      this.renderSection7(doc, estimate.assumptions);
      this.renderSection8(doc, estimate.changeManagement);
      this.renderSection9(doc, estimate.acceptanceCriteria);
      this.renderSection10(doc, estimate.additionalSections, meta.currency);

      this.addPageNumbers(doc);

      doc.end();
    });
  }

  private renderCoverPage(
    doc: PDFKit.PDFDocument,
    estimate: ProfessionalEstimateResult,
    meta: PdfMeta,
  ) {
    doc.rect(0, 0, doc.page.width, doc.page.height).fill(COLORS.primary);

    doc
      .fontSize(FONT_SIZES.title + 8)
      .fillColor(COLORS.white)
      .text('PROJECT ESTIMATE', 50, 200, { align: 'center' });

    doc
      .fontSize(FONT_SIZES.sectionTitle + 4)
      .text(estimate.projectOverview.projectName, 50, 260, { align: 'center' });

    doc.moveTo(150, 310).lineTo(445, 310).strokeColor(COLORS.white).lineWidth(1).stroke();

    doc.fontSize(FONT_SIZES.subTitle).text(`Version ${meta.version}`, 50, 340, { align: 'center' });

    doc.fontSize(FONT_SIZES.body + 2).text(
      `Client: ${estimate.projectOverview.clientName}`,
      50,
      380,
      { align: 'center' },
    );

    doc.text(`Date: ${estimate.projectOverview.date}`, 50, 400, { align: 'center' });

    const costDisplay = `${estimate.costCalculation.currency} ${this.formatNumber(estimate.costMin)} - ${this.formatNumber(estimate.costMax)}`;
    doc.fontSize(FONT_SIZES.subTitle).text(costDisplay, 50, 450, { align: 'center' });

    doc.text(
      `Timeline: ${estimate.timelineMinDays} - ${estimate.timelineMaxDays} days`,
      50,
      475,
      { align: 'center' },
    );

    doc
      .fontSize(FONT_SIZES.small)
      .fillColor('#c7d2fe')
      .text('Generated by Bolder Scope', 50, doc.page.height - 100, { align: 'center' })
      .text(`Confidence Score: ${estimate.confidenceScore}%`, 50, doc.page.height - 85, {
        align: 'center',
      });
  }

  private renderTableOfContents(doc: PDFKit.PDFDocument) {
    doc.addPage();
    this.sectionHeading(doc, 'TABLE OF CONTENTS', 0);

    const sections = [
      '1. Loyiha haqida umumiy ma\'lumot (Project Overview)',
      '2. Ish qamrovi (Scope)',
      '3. Texnik arxitektura (Technical Architecture)',
      '4. Ishlarni bo\'lib chiqish (Work Breakdown Structure)',
      '5. Vaqt jadvali (Timeline)',
      '6. Xarajatlar hisob-kitobi (Cost Calculation)',
      '7. Taxminlar va cheklovlar (Assumptions & Constraints)',
      '8. O\'zgarishlarni boshqarish (Change Management)',
      '9. Qabul qilish mezonlari (Acceptance Criteria)',
      '10. Qo\'shimcha bo\'limlar (Additional Sections)',
    ];

    doc.moveDown(1);
    for (const section of sections) {
      doc
        .fontSize(FONT_SIZES.body + 1)
        .fillColor(COLORS.dark)
        .text(section, { indent: 20 });
      doc.moveDown(0.5);
    }
  }

  private renderSection1(doc: PDFKit.PDFDocument, overview: ProfessionalEstimateResult['projectOverview']) {
    doc.addPage();
    this.sectionHeading(doc, '1. LOYIHA HAQIDA UMUMIY MA\'LUMOT', 1, 'Project Overview');

    this.labelValue(doc, 'Loyiha nomi', overview.projectName);
    this.labelValue(doc, 'Buyurtmachi', overview.clientName);
    this.labelValue(doc, 'Versiya', overview.version);
    this.labelValue(doc, 'Sana', overview.date);

    doc.moveDown(0.5);
    this.subHeading(doc, 'Loyiha tavsifi');
    doc.fontSize(FONT_SIZES.body).fillColor(COLORS.gray).text(overview.description);

    doc.moveDown(0.5);
    this.subHeading(doc, 'Loyiha maqsadlari');
    this.bulletList(doc, overview.goals);
  }

  private renderSection2(doc: PDFKit.PDFDocument, scope: ProfessionalEstimateResult['scope']) {
    doc.addPage();
    this.sectionHeading(doc, '2. ISH QAMROVI', 2, 'Scope');

    this.subHeading(doc, 'Qamrovga kiradi');
    this.bulletList(doc, scope.inScope);

    doc.moveDown(0.5);
    this.subHeading(doc, 'Qamrovdan tashqari');
    this.bulletList(doc, scope.outOfScope);

    doc.moveDown(0.5);
    this.subHeading(doc, 'Asosiy funksiyalar');
    for (const feature of scope.features) {
      doc
        .fontSize(FONT_SIZES.body)
        .fillColor(COLORS.dark)
        .text(`  [${feature.priority}] ${feature.name}`, { continued: true })
        .fillColor(COLORS.gray)
        .text(` - ${feature.description}`);
    }

    doc.moveDown(0.5);
    this.subHeading(doc, 'Modullar');
    this.bulletList(doc, scope.modules);

    doc.moveDown(0.5);
    this.subHeading(doc, 'Integratsiyalar');
    this.bulletList(doc, scope.integrations);

    doc.moveDown(0.5);
    this.subHeading(doc, 'Platformalar');
    this.bulletList(doc, scope.platforms);
  }

  private renderSection3(
    doc: PDFKit.PDFDocument,
    arch: ProfessionalEstimateResult['technicalArchitecture'],
  ) {
    doc.addPage();
    this.sectionHeading(doc, '3. TEXNIK ARXITEKTURA', 3, 'Technical Architecture');

    this.labelValue(doc, 'Arxitektura turi', arch.architectureType);
    doc.moveDown(0.5);

    const categories: Array<[string, string[]]> = [
      ['Frontend', arch.frontend],
      ['Backend', arch.backend],
      ['Ma\'lumotlar bazasi', arch.database],
      ['Hosting', arch.hosting],
      ['Cloud xizmatlari', arch.cloudServices],
      ['Uchinchi tomon xizmatlari', arch.thirdPartyServices],
    ];

    for (const [label, items] of categories) {
      this.subHeading(doc, label);
      this.bulletList(doc, items);
      doc.moveDown(0.3);
    }

    doc.moveDown(0.5);
    this.subHeading(doc, 'Arxitektura tavsifi');
    doc.fontSize(FONT_SIZES.body).fillColor(COLORS.gray).text(arch.architectureDiagramDescription);
  }

  private renderSection4(
    doc: PDFKit.PDFDocument,
    wbs: ProfessionalEstimateResult['wbs'],
    currency: string,
  ) {
    doc.addPage();
    this.sectionHeading(doc, '4. ISHLARNI BO\'LIB CHIQISH', 4, 'Work Breakdown Structure');

    doc
      .fontSize(FONT_SIZES.body)
      .fillColor(COLORS.dark)
      .text(
        `Umumiy soatlar: ${wbs.totalHoursMin} - ${wbs.totalHoursMax} soat  |  ` +
          `Kunlar: ${wbs.totalDaysMin} - ${wbs.totalDaysMax} kun`,
      );
    doc.moveDown(0.8);

    for (const mod of wbs.modules) {
      this.checkPageSpace(doc, 120);

      this.subHeading(doc, `${mod.moduleName}`);
      doc
        .fontSize(FONT_SIZES.small)
        .fillColor(COLORS.gray)
        .text(`${mod.description} | ${mod.totalHoursMin}-${mod.totalHoursMax} soat`);
      doc.moveDown(0.3);

      const tableTop = doc.y;
      const colWidths = [70, 140, 50, 60, 60, 75, 40];
      const headers = ['ID', 'Vazifa', 'Murakkablik', 'Soat (min)', 'Soat (max)', 'Mas\'ul', 'Holat'];

      this.tableHeader(doc, tableTop, colWidths, headers);

      let y = tableTop + 18;
      for (const task of mod.tasks) {
        this.checkPageSpace(doc, 20);
        y = doc.y;
        const row = [
          task.taskId,
          task.taskName,
          task.complexity,
          String(task.hoursMin),
          String(task.hoursMax),
          task.responsibleRole,
          task.status === 'NOT_STARTED' ? 'Kutilmoqda' : task.status,
        ];
        this.tableRow(doc, y, colWidths, row);
      }
      doc.moveDown(1);
    }
  }

  private renderSection5(doc: PDFKit.PDFDocument, timeline: ProfessionalEstimateResult['timeline']) {
    doc.addPage();
    this.sectionHeading(doc, '5. VAQT JADVALI', 5, 'Timeline');

    this.labelValue(doc, 'Boshlanish sanasi', timeline.startDate);
    this.labelValue(doc, 'Tugash sanasi', timeline.endDate);
    this.labelValue(doc, 'Umumiy haftalar', String(timeline.totalWeeks));
    this.labelValue(doc, 'Test bosqichi', `${timeline.testPhaseStart} - ${timeline.testPhaseEnd}`);
    this.labelValue(doc, 'Deploy sanasi', timeline.deployDate);

    doc.moveDown(0.8);
    this.subHeading(doc, 'Sprintlar');

    for (const sprint of timeline.sprints) {
      this.checkPageSpace(doc, 60);
      doc
        .fontSize(FONT_SIZES.body)
        .fillColor(COLORS.primary)
        .text(`Sprint ${sprint.sprintNumber}: ${sprint.name}`, { underline: true });
      doc
        .fontSize(FONT_SIZES.small)
        .fillColor(COLORS.gray)
        .text(`${sprint.startDate} - ${sprint.endDate}`);
      this.bulletList(doc, sprint.goals);
      doc.moveDown(0.4);
    }

    doc.moveDown(0.5);
    this.subHeading(doc, 'Milestonelar');
    for (const ms of timeline.milestones) {
      this.checkPageSpace(doc, 40);
      doc
        .fontSize(FONT_SIZES.body)
        .fillColor(COLORS.dark)
        .text(`${ms.date} - ${ms.name}`);
      this.bulletList(doc, ms.deliverables);
      doc.moveDown(0.3);
    }
  }

  private renderSection6(
    doc: PDFKit.PDFDocument,
    cost: ProfessionalEstimateResult['costCalculation'],
  ) {
    doc.addPage();
    this.sectionHeading(doc, '6. XARAJATLAR HISOB-KITOBI', 6, 'Cost Calculation');

    this.labelValue(doc, 'Umumiy ish soatlari', `${cost.totalHours} soat`);
    this.labelValue(doc, '1 soat narxi', `${cost.currency} ${this.formatNumber(cost.hourlyRate)}`);
    this.labelValue(doc, 'Umumiy loyiha qiymati', `${cost.currency} ${this.formatNumber(cost.totalCost)}`);
    this.labelValue(doc, 'Valyuta', cost.currency);
    this.labelValue(doc, 'Oldindan to\'lov', `${cost.advancePaymentPercent}% (${cost.currency} ${this.formatNumber(cost.advancePaymentAmount)})`);
    this.labelValue(doc, 'Qo\'shimcha ish narxi', `${cost.currency} ${this.formatNumber(cost.additionalWorkHourlyRate)}/soat`);
    this.labelValue(doc, 'Zaxira foizi', `${cost.contingencyPercent}% (${cost.currency} ${this.formatNumber(cost.contingencyAmount)})`);

    doc.moveDown(0.8);
    this.subHeading(doc, 'To\'lov bosqichlari');

    const payHeaders = ['Bosqich', 'Foiz', 'Summa', 'Trigger'];
    const payColWidths = [130, 60, 110, 195];
    this.tableHeader(doc, doc.y, payColWidths, payHeaders);

    for (const stage of cost.paymentStages) {
      this.checkPageSpace(doc, 20);
      this.tableRow(doc, doc.y, payColWidths, [
        stage.stageName,
        `${stage.percentage}%`,
        `${cost.currency} ${this.formatNumber(stage.amount)}`,
        stage.triggerMilestone,
      ]);
    }

    doc.moveDown(1);
    this.subHeading(doc, 'Modul bo\'yicha xarajatlar');

    const modHeaders = ['Modul', 'Soatlar', 'Narx'];
    const modColWidths = [230, 100, 165];
    this.tableHeader(doc, doc.y, modColWidths, modHeaders);

    for (const mod of cost.costBreakdownByModule) {
      this.checkPageSpace(doc, 20);
      this.tableRow(doc, doc.y, modColWidths, [
        mod.moduleName,
        String(mod.hours),
        `${cost.currency} ${this.formatNumber(mod.cost)}`,
      ]);
    }
  }

  private renderSection7(
    doc: PDFKit.PDFDocument,
    assumptions: ProfessionalEstimateResult['assumptions'],
  ) {
    doc.addPage();
    this.sectionHeading(doc, '7. TAXMINLAR VA CHEKLOVLAR', 7, 'Assumptions & Constraints');

    this.subHeading(doc, 'Asosiy taxminlar');
    this.bulletList(doc, assumptions.assumptions);

    doc.moveDown(0.5);
    this.subHeading(doc, 'Texnik cheklovlar');
    this.bulletList(doc, assumptions.technicalConstraints);

    doc.moveDown(0.5);
    this.subHeading(doc, 'Resurs cheklovlari');
    this.bulletList(doc, assumptions.resourceConstraints);

    doc.moveDown(0.5);
    this.subHeading(doc, 'Bog\'liqliklar');
    this.bulletList(doc, assumptions.dependencies);

    doc.moveDown(0.5);
    this.subHeading(doc, 'Xavflar');

    const riskHeaders = ['Xavf', 'Ta\'sir', 'Yechim'];
    const riskColWidths = [200, 60, 235];
    this.tableHeader(doc, doc.y, riskColWidths, riskHeaders);

    for (const risk of assumptions.risks) {
      this.checkPageSpace(doc, 20);
      this.tableRow(doc, doc.y, riskColWidths, [
        risk.risk,
        risk.impact,
        risk.mitigation,
      ]);
    }
  }

  private renderSection8(
    doc: PDFKit.PDFDocument,
    cm: ProfessionalEstimateResult['changeManagement'],
  ) {
    doc.addPage();
    this.sectionHeading(doc, '8. O\'ZGARISHLARNI BOSHQARISH', 8, 'Change Management');

    this.subHeading(doc, 'Scope o\'zgarish jarayoni');
    this.numberedList(doc, cm.scopeChangeProcess);

    doc.moveDown(0.5);
    this.subHeading(doc, 'Qo\'shimcha talablarni baholash');
    doc.fontSize(FONT_SIZES.body).fillColor(COLORS.gray).text(cm.additionalRequirementEvaluation);

    doc.moveDown(0.5);
    this.subHeading(doc, 'Tasdiqlash jarayoni');
    this.numberedList(doc, cm.approvalProcess);

    doc.moveDown(0.5);
    this.subHeading(doc, 'O\'zgarish so\'rovi shakli');
    this.bulletList(doc, cm.changeRequestTemplate.fields);
  }

  private renderSection9(
    doc: PDFKit.PDFDocument,
    ac: ProfessionalEstimateResult['acceptanceCriteria'],
  ) {
    doc.addPage();
    this.sectionHeading(doc, '9. QABUL QILISH MEZONLARI', 9, 'Acceptance Criteria');

    this.subHeading(doc, 'Qabul qilish shartlari');
    this.bulletList(doc, ac.acceptanceConditions);

    doc.moveDown(0.5);
    this.subHeading(doc, 'Test jarayoni');
    this.bulletList(doc, ac.testProcess);

    doc.moveDown(0.5);
    this.subHeading(doc, 'Demo topshirish');
    doc.fontSize(FONT_SIZES.body).fillColor(COLORS.gray).text(ac.demoDeliveryPlan);

    doc.moveDown(0.5);
    this.subHeading(doc, 'Ishga tushirish muhiti');
    this.bulletList(doc, ac.launchEnvironment);

    doc.moveDown(0.5);
    this.subHeading(doc, 'Texnik hujjat topshirish');
    this.bulletList(doc, ac.technicalDocumentation);
  }

  private renderSection10(
    doc: PDFKit.PDFDocument,
    additional: ProfessionalEstimateResult['additionalSections'],
    currency: string,
  ) {
    doc.addPage();
    this.sectionHeading(doc, '10. QO\'SHIMCHA BO\'LIMLAR', 10, 'Additional Sections');

    this.subHeading(doc, 'Resurs taqsimoti');
    const resHeaders = ['Rol', 'Soni', 'Band'];
    const resColWidths = [230, 80, 185];
    this.tableHeader(doc, doc.y, resColWidths, resHeaders);

    for (const res of additional.resourceAllocation) {
      this.checkPageSpace(doc, 20);
      this.tableRow(doc, doc.y, resColWidths, [
        res.role,
        String(res.count),
        res.allocation,
      ]);
    }

    doc.moveDown(0.8);
    this.subHeading(doc, 'Texnik qo\'llab-quvvatlash rejasi');
    doc.fontSize(FONT_SIZES.body).fillColor(COLORS.gray).text(additional.techSupportPlan);

    doc.moveDown(0.5);
    this.labelValue(doc, 'Kafolat muddati', `${additional.warrantyPeriodMonths} oy`);
    this.labelValue(doc, 'Oylik texnik xizmat narxi', `${currency} ${this.formatNumber(additional.monthlyServiceCost)}`);

    doc.moveDown(0.5);
    this.subHeading(doc, 'Kengaytirish imkoniyatlari');
    this.bulletList(doc, additional.scalingOptions);

    doc.moveDown(0.5);
    this.subHeading(doc, 'Kelajak rivojlantirish bosqichlari');
    for (const phase of additional.futureDevelopmentPhases) {
      this.checkPageSpace(doc, 50);
      doc
        .fontSize(FONT_SIZES.body)
        .fillColor(COLORS.primary)
        .text(phase.phaseName, { underline: true });
      doc.fontSize(FONT_SIZES.small).fillColor(COLORS.gray).text(phase.description);
      doc.text(`Muddat: ${phase.estimatedTimeline} | Narx: ${currency} ${this.formatNumber(phase.estimatedCost)}`);
      doc.moveDown(0.4);
    }
  }

  // ── Helper Methods ──

  private sectionHeading(
    doc: PDFKit.PDFDocument,
    title: string,
    _sectionNumber: number,
    subtitle?: string,
  ) {
    doc
      .fontSize(FONT_SIZES.sectionTitle)
      .fillColor(COLORS.primary)
      .text(title);

    if (subtitle) {
      doc
        .fontSize(FONT_SIZES.body)
        .fillColor(COLORS.lightGray)
        .text(subtitle);
    }

    doc
      .moveTo(50, doc.y + 4)
      .lineTo(545, doc.y + 4)
      .strokeColor(COLORS.primary)
      .lineWidth(1.5)
      .stroke();

    doc.moveDown(0.8);
  }

  private subHeading(doc: PDFKit.PDFDocument, text: string) {
    doc
      .fontSize(FONT_SIZES.subTitle)
      .fillColor(COLORS.dark)
      .text(text);
    doc.moveDown(0.3);
  }

  private labelValue(doc: PDFKit.PDFDocument, label: string, value: string) {
    doc
      .fontSize(FONT_SIZES.body)
      .fillColor(COLORS.gray)
      .text(`${label}: `, { continued: true })
      .fillColor(COLORS.dark)
      .text(value);
  }

  private bulletList(doc: PDFKit.PDFDocument, items: string[]) {
    for (const item of items) {
      doc
        .fontSize(FONT_SIZES.body)
        .fillColor(COLORS.gray)
        .text(`  \u2022  ${item}`, { indent: 10 });
    }
  }

  private numberedList(doc: PDFKit.PDFDocument, items: string[]) {
    items.forEach((item, i) => {
      doc
        .fontSize(FONT_SIZES.body)
        .fillColor(COLORS.gray)
        .text(`  ${i + 1}. ${item}`, { indent: 10 });
    });
  }

  private tableHeader(
    doc: PDFKit.PDFDocument,
    y: number,
    colWidths: number[],
    headers: string[],
  ) {
    const rowHeight = 16;
    doc.rect(50, y, colWidths.reduce((a, b) => a + b, 0), rowHeight).fill(COLORS.primaryLight);

    let x = 54;
    for (let i = 0; i < headers.length; i++) {
      doc
        .fontSize(FONT_SIZES.small)
        .fillColor(COLORS.primary)
        .text(headers[i], x, y + 3, { width: colWidths[i] - 8, lineBreak: false });
      x += colWidths[i];
    }
    doc.y = y + rowHeight + 2;
  }

  private tableRow(
    doc: PDFKit.PDFDocument,
    y: number,
    colWidths: number[],
    values: string[],
  ) {
    let x = 54;
    for (let i = 0; i < values.length; i++) {
      doc
        .fontSize(FONT_SIZES.caption)
        .fillColor(COLORS.gray)
        .text(values[i], x, y + 2, { width: colWidths[i] - 8, lineBreak: false });
      x += colWidths[i];
    }

    const totalWidth = colWidths.reduce((a, b) => a + b, 0);
    doc
      .moveTo(50, y + 14)
      .lineTo(50 + totalWidth, y + 14)
      .strokeColor(COLORS.border)
      .lineWidth(0.5)
      .stroke();

    doc.y = y + 16;
  }

  private checkPageSpace(doc: PDFKit.PDFDocument, requiredSpace: number) {
    if (doc.y + requiredSpace > doc.page.height - 80) {
      doc.addPage();
    }
  }

  private addPageNumbers(doc: PDFKit.PDFDocument) {
    const range = doc.bufferedPageRange();
    for (let i = 1; i < range.count; i++) {
      doc.switchToPage(i);
      doc
        .fontSize(FONT_SIZES.caption)
        .fillColor(COLORS.lightGray)
        .text(`${i + 1} / ${range.count}`, 50, doc.page.height - 40, {
          align: 'center',
          width: doc.page.width - 100,
        });
    }
  }

  private formatNumber(n: number): string {
    return n.toLocaleString('en-US', { maximumFractionDigits: 0 });
  }
}
